export const profileData = {
  id: 'developer',
  name: 'Васильев Степан Денисович',
  description:
    'Backend-разработчик из Москвы с опытом fullstack- и frontend-разработки. Создаю веб-приложения на React, Next.js и TypeScript, разрабатываю backend на Python и FastAPI. Работаю с PostgreSQL, REST API, Docker и Nginx; веду проекты от обсуждения задачи с заказчиком до деплоя.',
  githubUrl: 'https://github.com/luhgeek1',
  linkedinUrl: null,
  skills: [
    { id: 'skill-typescript', name: 'TypeScript', category: 'Language' },
    { id: 'skill-javascript', name: 'JavaScript', category: 'Language' },
    { id: 'skill-python', name: 'Python', category: 'Language' },
    { id: 'skill-go', name: 'Go', category: 'Language' },
    { id: 'skill-nodejs', name: 'Node.js', category: 'Runtime' },
    { id: 'skill-fastapi', name: 'FastAPI', category: 'Framework' },
    { id: 'skill-react', name: 'React', category: 'Library' },
    { id: 'skill-nextjs', name: 'Next.js', category: 'Framework' },
    { id: 'skill-postgresql', name: 'PostgreSQL', category: 'Database' },
    { id: 'skill-mysql', name: 'MySQL', category: 'Database' },
    { id: 'skill-redis', name: 'Redis', category: 'Database' },
    { id: 'skill-sqlalchemy', name: 'SQLAlchemy', category: 'ORM' },
    { id: 'skill-rest-api', name: 'REST API', category: 'API' },
    { id: 'skill-docker', name: 'Docker', category: 'DevOps' },
    { id: 'skill-nginx', name: 'Nginx', category: 'DevOps' },
    { id: 'skill-git', name: 'Git', category: 'Version Control' },
    { id: 'skill-github', name: 'GitHub', category: 'Platform' },
    { id: 'skill-english', name: 'English (B2)', category: 'Foreign Language' },
  ],
  experience: [
    {
      id: 'experience-margin',
      company: 'Margin',
      position: 'Frontend-разработчик',
      startDate: new Date('2026-06-01T00:00:00.000Z'),
      endDate: null,
      achievements: [
        'Разработка и доработка пользовательского интерфейса на React и TypeScript.',
        'Реализация новых продуктовых функций и интеграция frontend с backend через REST API.',
        'Работа с состоянием приложения и обработкой данных.',
        'Проведение code review и участие в улучшении качества кода команды.',
      ],
    },
    {
      id: 'experience-freelance',
      company: 'Freelance',
      position: 'Fullstack-разработчик',
      startDate: new Date('2025-05-01T00:00:00.000Z'),
      endDate: null,
      achievements: [
        'Разработка сайтов и веб-приложений для заказчиков на React, Next.js и TypeScript.',
        'Разработка backend на FastAPI и интеграция с API.',
        'Обсуждение задач с клиентами, оценка сроков и самостоятельное ведение проектов.',
        'Реализация авторизации, адаптивного интерфейса и пользовательских сценариев.',
        'Полный цикл разработки отдельных проектов: от создания до деплоя с Git, Docker и Nginx.',
      ],
    },
    {
      id: 'experience-carpe-diem',
      company: 'Carpe diem',
      position: 'Frontend-разработчик',
      startDate: new Date('2026-02-01T00:00:00.000Z'),
      endDate: new Date('2026-09-01T00:00:00.000Z'),
      achievements: [
        'Разработка пользовательского интерфейса и продуктовых функций на React и TypeScript.',
        'Интеграция frontend с backend и API.',
        'Работа с данными и состояниями приложения.',
        'Участие в развитии продукта внутри стартап-команды.',
      ],
    },
  ],
  projects: [
    {
      id: 'project-codemetrics',
      name: 'CodeMetrics',
      description:
        'Платформа анализа кода и метрик проектов с дашбордами по репозиториям, разработчикам и активности команды. Агрегирует данные из SferaCode и использует кеширование для ускорения запросов.',
      repositoryUrl: 'https://github.com/luhgeek1/CodeMetrics1',
      liveUrl: 'https://code-metrics-psi.vercel.app/',
      technologies: [
        'TypeScript',
        'React',
        'Vite',
        'Tailwind CSS',
        'Python',
        'FastAPI',
        'PostgreSQL',
        'Redis',
        'Docker',
        'Nginx',
      ],
    },
    {
      id: 'project-books-exchange',
      name: 'BooksExchange',
      description:
        'Корпоративная платформа для обмена книгами. Пользователи публикуют книги и места обмена, ищут доступные издания и оставляют отзывы; администратор модерирует контент и просматривает статистику.',
      repositoryUrl: 'https://github.com/laughinme/BooksExchange',
      liveUrl: 'https://books-exchange.vercel.app/',
      technologies: [
        'TypeScript',
        'React',
        'Vite',
        'Python',
        'FastAPI',
        'PostgreSQL',
        'Docker',
      ],
    },
    {
      id: 'project-auto-spare-parts',
      name: 'AutoSpareParts',
      description:
        'Маркетплейс автозапчастей для оптовых заказов из Дубая и покупок у локальных продавцов. MVP включает каталог, карточки запчастей, оформление заказов и витрину продавцов.',
      repositoryUrl: 'https://github.com/laughinme/AutoSpareParts',
      liveUrl: 'https://auto-spare-parts-gules.vercel.app/',
      technologies: ['Python', 'TypeScript', 'Kotlin', 'Docker', 'Nginx'],
    },
    {
      id: 'project-t-match',
      name: 'T-Match',
      description:
        'Платформа знакомств с персональной лентой на основе анкет, поведения пользователей и категорий транзакций. Использует ML-ранжирование с объяснением рекомендаций, взаимные симпатии, чат и механизмы блокировки и жалоб.',
      repositoryUrl: 'https://github.com/luhgeek1/T-match',
      liveUrl: 'https://team-26-prod-5df88b.pages.prodcontest.ru',
      technologies: [
        'TypeScript',
        'Python',
        'FastAPI',
        'React',
        'Vite',
        'PostgreSQL',
        'Redis',
        'CatBoost',
        'Qdrant',
        'MinIO',
        'Centrifugo',
        'Docker',
      ],
    },
    {
      id: 'project-orbitguard',
      name: 'OrbitGuard',
      description:
        'Сервис проектирования спутниковых группировок с анализом непрерывности связи между клиентами и наземными шлюзами. Моделирует отказы, рассчитывает доступность и перерывы связи, визуализирует маршруты на 2D-карте и 3D-глобусе.',
      repositoryUrl: 'https://github.com/luhgeek1/Orb1tGuard',
      liveUrl: 'https://orbitguard-frontend.vercel.app',
      technologies: [
        'TypeScript',
        'Python',
        'FastAPI',
        'Next.js',
        'React',
        'Three.js',
        'PostgreSQL',
        'Redis',
        'SQLAlchemy',
        'NumPy',
        'Docker',
      ],
    },
    {
      id: 'project-robosim',
      name: 'RoboSim / РобоМера',
      description:
        'Сервис оценки роботизации складов, больниц и аэропортов: подбирает роботов, рассчитывает размер парка и экономическую эффективность, моделирует работу роботов на плане объекта и формирует отчёты.',
      repositoryUrl: 'https://github.com/luhgeek1/robosim-studio-hack',
      liveUrl: 'https://prooood.ru/',
      technologies: [
        'TypeScript',
        'Python',
        'FastAPI',
        'React',
        'Vite',
        'Three.js',
        'PostgreSQL',
        'Redis',
        'SimPy',
        'arq',
        'Docker',
        'Nginx',
      ],
    },
    {
      id: 'project-righteous-rides',
      name: 'Righteous Rides',
      description:
        'Веб-платформа для аренды премиальных автомобилей и автомобильных услуг. Содержит каталог автопарка, отправку заявок, личный кабинет и панель администратора для управления автомобилями, фотографиями и контентом.',
      repositoryUrl: 'https://github.com/luhgeek1/car-sharing',
      liveUrl: null,
      technologies: [
        'Python',
        'FastAPI',
        'SQLAlchemy',
        'Next.js',
        'React',
        'TypeScript',
        'Tailwind CSS',
        'PostgreSQL',
        'Redis',
        'MinIO',
        'Docker',
        'Nginx',
      ],
    },
  ],
};
